import type { User, Listing, Booking, Conversation, Notification, AdminStats } from "@/types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Alex Rivera",
    email: "alex@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    role: "seller",
    bio: "Professional photographer and vintage electronics collector.",
    location: "San Francisco, CA",
    rating: 4.9,
    reviewCount: 127,
    joinedAt: "2022-03-15",
    isVerified: true,
    totalSales: 312,
    totalEarnings: 48500,
  },
  {
    id: "u2",
    name: "Jordan Kim",
    email: "jordan@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
    role: "buyer",
    bio: "Tech enthusiast and home improvement hobbyist.",
    location: "Austin, TX",
    rating: 4.7,
    reviewCount: 43,
    joinedAt: "2023-01-10",
    isVerified: true,
    totalSales: 15,
    totalEarnings: 2300,
  },
  {
    id: "u3",
    name: "Sam Chen",
    email: "sam@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sam",
    role: "seller",
    bio: "Fashion designer selling handmade and curated items.",
    location: "New York, NY",
    rating: 4.8,
    reviewCount: 89,
    joinedAt: "2021-11-05",
    isVerified: true,
    totalSales: 204,
    totalEarnings: 31200,
  },
  {
    id: "u4",
    name: "Morgan Taylor",
    email: "morgan@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan",
    role: "admin",
    bio: "Platform administrator.",
    location: "Seattle, WA",
    rating: 5.0,
    reviewCount: 0,
    joinedAt: "2020-06-01",
    isVerified: true,
  },
];

export const mockListings: Listing[] = [
  {
    id: "l1",
    title: "Sony Alpha A7 III Mirrorless Camera",
    description:
      "Professional full-frame mirrorless camera in excellent condition. Comes with the original box, two batteries, charger, and 28-70mm kit lens. Only 12,000 shutter count. Perfect for photographers upgrading their kit.",
    price: 1800,
    category: "Electronics",
    condition: "Like New",
    location: "San Francisco, CA",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80",
    ],
    seller: mockUsers[0],
    rating: 4.9,
    reviewCount: 24,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    isActive: true,
    isFeatured: true,
    views: 342,
    saves: 56,
    tags: ["camera", "sony", "mirrorless", "photography"],
  },
  {
    id: "l2",
    title: "Vintage Leather Jacket – 1970s Americana",
    description:
      "Authentic 1970s brown leather motorcycle jacket. Size M/L. Some natural wear consistent with age that adds to its character. A timeless piece for any wardrobe.",
    price: 320,
    category: "Fashion",
    condition: "Good",
    location: "New York, NY",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80",
    ],
    seller: mockUsers[2],
    rating: 4.8,
    reviewCount: 18,
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
    isActive: true,
    isFeatured: true,
    views: 215,
    saves: 38,
    tags: ["jacket", "vintage", "leather", "fashion"],
  },
  {
    id: "l3",
    title: "Standing Desk – Electric Height Adjustable",
    description:
      "FlexiSpot E7 standing desk, 60x24 inches, bamboo top. Memory presets for 4 heights. Works perfectly. Selling because moving to a smaller office.",
    price: 450,
    category: "Home & Garden",
    condition: "Like New",
    location: "Austin, TX",
    images: [
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
    ],
    seller: mockUsers[1],
    rating: 4.7,
    reviewCount: 9,
    createdAt: "2024-01-22",
    updatedAt: "2024-01-22",
    isActive: true,
    isFeatured: false,
    views: 178,
    saves: 22,
    tags: ["desk", "standing", "office", "ergonomic"],
  },
  {
    id: "l4",
    title: "Trek FX3 Hybrid Bike – 2022",
    description:
      "Barely used Trek FX3 fitness hybrid bike, size M. Shimano 24-speed drivetrain. Hydraulic disc brakes. Perfect for commuting or weekend rides.",
    price: 680,
    category: "Sports",
    condition: "Like New",
    location: "San Francisco, CA",
    images: [
      "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80",
    ],
    seller: mockUsers[0],
    rating: 4.9,
    reviewCount: 5,
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
    isActive: true,
    isFeatured: true,
    views: 290,
    saves: 47,
    tags: ["bike", "trek", "hybrid", "cycling"],
  },
  {
    id: "l5",
    title: "MacBook Pro 14\" M3 Pro – 2023",
    description:
      "Apple MacBook Pro 14-inch with M3 Pro chip, 18GB RAM, 512GB SSD. Space Gray. AppleCare+ until 2026. Includes original charger and box.",
    price: 1650,
    category: "Electronics",
    condition: "Like New",
    location: "New York, NY",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
    ],
    seller: mockUsers[2],
    rating: 5.0,
    reviewCount: 12,
    createdAt: "2024-01-28",
    updatedAt: "2024-01-28",
    isActive: true,
    isFeatured: true,
    views: 511,
    saves: 89,
    tags: ["macbook", "apple", "laptop", "m3"],
  },
  {
    id: "l6",
    title: "Web Development Services – React & Node.js",
    description:
      "Full-stack web developer offering project-based work. Specialise in React, Next.js, Node.js, and PostgreSQL. Portfolio available on request. Fast turnaround.",
    price: 85,
    category: "Services",
    condition: "New",
    location: "Remote",
    images: [
      "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
    ],
    seller: mockUsers[1],
    rating: 4.8,
    reviewCount: 31,
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
    isActive: true,
    isFeatured: false,
    views: 423,
    saves: 64,
    tags: ["web development", "react", "nodejs", "freelance"],
  },
];

export const mockBookings: Booking[] = [
  {
    id: "b1",
    listing: mockListings[0],
    buyer: mockUsers[1],
    seller: mockUsers[0],
    status: "confirmed",
    startDate: "2024-02-10",
    totalAmount: 1800,
    notes: "Please hold until I can arrange pickup.",
    createdAt: "2024-02-05",
    updatedAt: "2024-02-06",
  },
  {
    id: "b2",
    listing: mockListings[4],
    buyer: mockUsers[1],
    seller: mockUsers[2],
    status: "pending",
    startDate: "2024-02-15",
    totalAmount: 1650,
    createdAt: "2024-02-08",
    updatedAt: "2024-02-08",
  },
  {
    id: "b3",
    listing: mockListings[1],
    buyer: mockUsers[0],
    seller: mockUsers[2],
    status: "completed",
    startDate: "2024-01-28",
    totalAmount: 320,
    createdAt: "2024-01-24",
    updatedAt: "2024-01-30",
  },
];

export const mockConversations: Conversation[] = [
  {
    id: "c1",
    participants: [mockUsers[0], mockUsers[1]],
    listing: mockListings[0],
    lastMessage: {
      id: "m3",
      content: "Sure, I can do Saturday morning. Does 10am work?",
      sender: mockUsers[0],
      receiver: mockUsers[1],
      conversationId: "c1",
      createdAt: "2024-02-08T14:32:00Z",
      isRead: false,
    },
    unreadCount: 2,
    updatedAt: "2024-02-08T14:32:00Z",
  },
  {
    id: "c2",
    participants: [mockUsers[1], mockUsers[2]],
    listing: mockListings[4],
    lastMessage: {
      id: "m6",
      content: "Is the MacBook still available?",
      sender: mockUsers[1],
      receiver: mockUsers[2],
      conversationId: "c2",
      createdAt: "2024-02-07T09:15:00Z",
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: "2024-02-07T09:15:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "booking",
    title: "Booking Confirmed",
    body: "Your booking for Sony Alpha A7 III has been confirmed.",
    isRead: false,
    link: "/dashboard/bookings",
    createdAt: "2024-02-06T10:00:00Z",
  },
  {
    id: "n2",
    type: "message",
    title: "New Message",
    body: "Alex Rivera sent you a message about the camera.",
    isRead: false,
    link: "/dashboard/messages",
    createdAt: "2024-02-08T14:32:00Z",
  },
  {
    id: "n3",
    type: "review",
    title: "New Review",
    body: "You received a 5-star review from Jordan Kim.",
    isRead: true,
    link: "/profile/u1",
    createdAt: "2024-01-30T16:45:00Z",
  },
  {
    id: "n4",
    type: "payment",
    title: "Payment Received",
    body: "You received $320 for Vintage Leather Jacket.",
    isRead: true,
    link: "/dashboard/bookings",
    createdAt: "2024-01-30T12:00:00Z",
  },
];

export const mockAdminStats: AdminStats = {
  totalUsers: 12847,
  totalListings: 48293,
  totalBookings: 9412,
  totalRevenue: 1284750,
  activeUsers: 3821,
  newUsersThisMonth: 847,
  newListingsThisMonth: 3201,
  revenueThisMonth: 98430,
};

export const CATEGORIES = [
  { name: "Electronics", icon: "Laptop", count: 8432 },
  { name: "Fashion", icon: "Shirt", count: 12847 },
  { name: "Home & Garden", icon: "Home", count: 6291 },
  { name: "Sports", icon: "Dumbbell", count: 4183 },
  { name: "Vehicles", icon: "Car", count: 2847 },
  { name: "Services", icon: "Wrench", count: 5621 },
  { name: "Real Estate", icon: "Building2", count: 1924 },
  { name: "Jobs", icon: "Briefcase", count: 3148 },
];
